<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<% 
	String publicMerchantId = request.getParameter("publicMerchantId");
	String urlAction = request.getParameter("urlAction");
	String urlResponse = request.getParameter("urlResponse");
	String paymentNumOrder = request.getParameter("paymentNumOrder");
%>


<form id="webForm" action="">
	<label>Payment Num Order</label>
	<input type="text" id="paymentNumOrder" name="paymentNumOrder" value="<%=paymentNumOrder%>"/><br/>
	<label>Name</label>
	<input type="text" id="name" name="name" /><br/>
	<label>CC Number</label>
	<input type="text" id="number" name="number" /><br/>
	<label>Month</label>
	<input type="text" id="expiryMonth" name="expiryMonth"/><br/>
	<label>Year</label>
	<input type="text" id="expiryYear" name="expiryYear"/><br/>
	<label>CVV</label>
	<input type="text" id="cvv" name="cvv" /><br/>
	<label>Total Amount</label>
	<input type="text" id="totalAmount" name="totalAmount" /><br/>
	<label>Months</label>
	<input type="text" id="months" name="months" value="0"/><br/>
	<label>Idiom</label>
	<input type="text" id="idiom" name="idiom" value="es"/><br/>
	<label>Currrency</label>
	<input type="text" id="currency" name="currency" value="COP"/><br/>
	<input type="hidden" id="isTest" name="isTest" value="true"/>
	<button type="button"id="btnSend" onclick="getToken();">Enviar</button>
</form>

<script>
function getToken(){
	var amount = document.getElementById("totalAmount").value;//Mostrado en la pagina $350000 tres cientos cincuenta mil pesos. esperado por kushki 350000.00  
	var data = "{\"card\": {\"name\": \""+document.getElementById("name").value+"\",\"number\":\""+ document.getElementById("number").value+"\",\"expiryMonth\":\""+document.getElementById("expiryMonth").value
			+"\",\"expiryYear\":\""+ document.getElementById("expiryYear").value+"\",\"cvv\":\""+document.getElementById("cvv").value+"\"},\"totalAmount\":"+parseFloat(amount.slice(0,-2)+"."+amount.slice(amount.length-2,amount.length)).toFixed(2)
			+",\"currency\": \"COP\"}";

	$.ajax({
	    url: "https://api-uat.kushkipagos.com/v1/tokens",
	    headers: {
	        'Content-Type':'application/json',
	        'Public-Merchant-Id':'<%=publicMerchantId%>'//example 10000002825331705579151380634343
	    },
	    method: 'POST',
	    dataType: 'json',
	    data: data
	  })
	  .always(function(datas){
	    	if(datas.token != undefined){
	    		var chargeCreditCardForm = document.createElement("FORM");
	    		chargeCreditCardForm.action ='<%=urlAction%>';//Url action to call CommonGateway.decodePaymentResponse
	    		chargeCreditCardForm.method = "POST";
	    		
	    		var urlResponse = document.createElement("input");
	    		urlResponse.type = "text";
	    		urlResponse.name = "urlResponse";
	    		urlResponse.id = "urlResponse";
	    		urlResponse.value = '<%=urlResponse%>';
	    		
	    		var kushki_token = document.createElement("input");
	    		kushki_token.type = "text";
	    		kushki_token.name = "kushki-token";
	    		kushki_token.id = "kushki-token";
	    		kushki_token.value = datas.token;
	    		
	    		var privateMerchantId = document.createElement("input");
	    		privateMerchantId.type = "text";
	    		privateMerchantId.name = "privateMerchantId";
	    		privateMerchantId.id = "privateMerchantId";
	    		privateMerchantId.value = "10000002825366457629151380634343";
	    		
	    		var months = document.createElement("input");
	    		months.type = "text";
	    		months.name = "months";
	    		months.id = "months";
	    		months.value = document.getElementById("months").value;

	    		var totalAmount = document.createElement("input");
	    		totalAmount.type = "text";
	    		totalAmount.name = "totalAmount";
	    		totalAmount.id = "totalAmount";
	    		totalAmount.value = document.getElementById("totalAmount").value;//You can have field that keep this value or can be capture from the previous call
	    		
	    		var isTest = document.createElement("input");
	    		isTest.type = "text";
	    		isTest.name = "isTest";
	    		isTest.id = "isTest";
	    		isTest.value = document.getElementById("isTest").value;//true or (default false) //You can have field that keep this value or can be capture from the previous call
	    		
	    		var paymentNumOrder = document.createElement("input");
	    		paymentNumOrder.type = "text";
	    		paymentNumOrder.name = "paymentNumOrder";
	    		paymentNumOrder.id = "paymentNumOrder";
	    		paymentNumOrder.value = document.getElementById("paymentNumOrder").value;//value generated by CommonGateway.getNewPaymentNumOrder()
	    		
	    		var currency = document.createElement("input");
	    		currency.type = "text";
	    		currency.name = "currency";
	    		currency.id = "currency";
	    		currency.value = document.getElementById("currency").value;//USD or (default COP) //You can have field that keep this value or can be capture from the previous call
	    		
	    		var idiom = document.createElement("input");
	    		idiom.type = "text";
	    		idiom.name = "idiom";
	    		idiom.id = "idiom";
	    		idiom.value = document.getElementById("idiom").value;//en or (default es)
	    		
	    		chargeCreditCardForm.appendChild(kushki_token);
	    		chargeCreditCardForm.appendChild(privateMerchantId);
	    		chargeCreditCardForm.appendChild(months);//if this value is not sent to the backend the default will be [0]
	    		chargeCreditCardForm.appendChild(totalAmount);
	    		chargeCreditCardForm.appendChild(isTest);//if this value is not sent to the backend the default will be [FALSE]
	    		chargeCreditCardForm.appendChild(paymentNumOrder);
	    		chargeCreditCardForm.appendChild(currency);//if this value is not sent to the backend the default will be [COP]
	    		chargeCreditCardForm.appendChild(idiom);//if this value is not sent to the backend the default will be [es]
	    		document.body.appendChild(chargeCreditCardForm);
	    		chargeCreditCardForm.submit();
	    		
	    		
	    		//Another method to get the action to work
	    		//Make sure to encode the parameters to URL format, for example replace a blank space with %20
	    		//and then concat them after every equals (=) sign
	    		//window.location.href 
	    			//= urlAction+"?urlResponse=&privateMerchantId=&kushki-token=&months=&totalAmount=&isTest=&paymentNumOrder=&currency=&idiom=";

	      }else{
	    	  alert(datas.responseJSON.code+":"+datas.responseJSON.message);
	      }
	    });
}
</script>
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
</body>
</html>